
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 07 01:50:03 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 47;
  public static final int CONST = 6;
  public static final int NAMESPACE = 5;
  public static final int SLASH = 31;
  public static final int NOT_EQUAL = 34;
  public static final int SMALLER = 36;
  public static final int LPAREN = 16;
  public static final int SEMI = 11;
  public static final int CONTINUE = 27;
  public static final int NUM_CONST = 46;
  public static final int DECR = 42;
  public static final int FOR = 28;
  public static final int MINUS = 29;
  public static final int STAR = 30;
  public static final int STATIC = 15;
  public static final int RPAREN = 17;
  public static final int LSQR = 7;
  public static final int AND = 39;
  public static final int OR = 40;
  public static final int COMMA = 9;
  public static final int CLASS = 13;
  public static final int INC = 41;
  public static final int PLUS = 21;
  public static final int IF = 24;
  public static final int DOT = 44;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int EQUAL = 10;
  public static final int NEW = 25;
  public static final int error = 1;
  public static final int PERCENT = 32;
  public static final int IDENT = 45;
  public static final int BIGGER = 35;
  public static final int BREAK = 22;
  public static final int VOID = 18;
  public static final int ARROW = 43;
  public static final int COMPARE = 33;
  public static final int COLON = 12;
  public static final int LBRACE = 3;
  public static final int ELSE = 23;
  public static final int READ = 26;
  public static final int RSQR = 8;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 14;
  public static final int PROG = 2;
  public static final int LEQ = 38;
  public static final int BOOL_CONST = 48;
  public static final int PRINT = 19;
  public static final int BEQ = 37;
}

